version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
      - image: circleci/mongo:4.0.3
    steps:
      - checkout
      - run: "npm install"
      - run: "npm run build"
      - run: "npm run start"
      - run: "npm run seed"
      - run: "npm run test"
